baseURL: 'https://actu.fit'
languageCode: 'fr-fr'
DefaultContentLanguage: "fr"
title: 'Actu Fit'
theme: 'chunky-poster'
paginate: 2
enableInlineShortcodes: true
footnoteReturnLinkContents: "^"

params:
  description: 'Bien choisir son équipement de sport.'
  homepageImage: "/images/logo.png"
  prismJS:
    enable: false
  commento:
    enable: false

taxonomies:
  tag: "tags"

menu:
  main:
    - identifier: "home"
      name: "Accueil"
      url: "/"
      weight: 1.
    - identifier: "benchmarks"
      name: "Comparatifs"
      url: "/tags/comparatifs/"
      weight: 2
    - identifier: "about"
      name: "À propos"
      url: "/a-propos/"
      weight: 3
